
spring:
  datasource:
    url: jdbc:mysql://localhost/jpa_many_to_many_using_list?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: your-password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8087

