spring:
  datasource:
    url: jdbc:mysql://localhost/jpa_one_to_one_unidirectional_mapping?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: your-password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

