spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost/account_verification_module_db?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
# 账号等敏感信息设置在 ~/.spring-boot-devtools.yml 文件中，格式如下
#spring:
#  mail:
#    username: your-email-address
#    password: your-verification-code
  mail:
    host: smtp.163.com
    port: 465
    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: true
  messages:
    basename: i18n/messages