
# 账号等敏感信息设置在 ~/.spring-boot-devtools.yml 文件中，格式如下
#spring:
#  mail:
#    username: your-email-address
#    password: your-verification-code
spring:
  mail:
    host: smtp.163.com
    port: 465
    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: true
